label ch0_main:
    stop music fadeout 2.0
    scene bg bedroom
    with dissolve_scene_full
    play music t2
    show character 3c zorder 2 at t11
    mc "hello."
    c "Hi there! How are you doing today?" 
    mc "good."
    c 3j1 "That's good to hear! Do you have any plans for the rest of the day?"
    mc "no... i like to hear yours."
    c 3f "Well, I don't have much planned either. I might just read some books and relax."
    c "..."
    c 3k "Is something wrong?"
    c "No! everythings good! I just don't know what to do..."
    c 3e "I see. Well, you don't have to do anything special. It's fine to just relax occasionally."
    c "But hey! Do you... do you like to go out with me a little?"
    c 3w "{i}blushes{/i} Really? You want to go out with me?"
    mc "Yes! I really passionate about you!"
    show character 3e zorder 2 at hf11
    c "{i}blushes more{/i} Really? You're very passionate about me..?"
    mc "Yes! I'm serious right now!"
    c "{i}blushes even more now{/i} You... You want to go out together? Just the two of us?"
    mc "Yes! that's my wish!"
    c 3i "Really...? Just... The two of us?"
    mc "Yes! just me and you! I actually had a plan. I wanted to see that your workless or not."
    c 3j "{i}blushes some more{/i} You planned something for us...? You really did...?"
    mc "Yes... I always know what you like to do. like gaming, right?"
    c "R-Really? You actually remember that I like gaming...?"
    mc "Yes! I like and know boys so much! especially you! I love you more than any boys I saw. but I've never seen a polite person like you."
    c 3f1 "{i}breathless{/i} S-So... You're saying you really love me...? You... You really love me..?"
    mc "Yeah! you're hearing it straight from my mouth. so it's totally true."
    c "{i}speechless for a moment, and then finally manages to say something{/i} I... I can't believe this... You... You really love me...?"
    mc "yes, I really love you!"
    "I hug him. He gets extremely flustered by the hug, and is completely speechless for a while, but eventually manages to get out 3 words."
    show character 4i5 zorder 2 at hf11
    c "You... You h-hugged me...?"
    mc "Indeed! I show my love to people like this. but they don't notice me or don't count a hug as love...."
    "He gets even more flustered, his face becomes red as a tomato."
    c 4i6 "Y-You really s-show your love like that...? Just by hugging someone?"
    mc "Yes! you heard it right!"
    "He starts feeling even more breathless now, as he manages to get out a few words."
    c 4i "You know... You're the first person who has ever shown this much affection to me..."
    mc "I myself didn't seen someone enjoys my existence or love me in a real way... but I know everything about you...."
    "He gets even more flustered and red at that."
    show character 4f1 zorder 2 at s11
    c "You... You know everything about me..?"
    c "T-Then... T-Then... Do you know where I used to live as a child...?"
    mc "Yes"
    show character 4f1 zorder 2 at hf11
    c "W-What? You know that too?"
    mc "yes!"
    c "Y-You know almost everything about me?!"
    mc "yes"
    "He blushes extremely and feels like his heart is going to explode."
    c "Y-You really remember almost e-everything... A-About me...?"
    mc "Yes! I have to know everything about the one I love."
    "He still gets extremely flustered, and manages to get out a few words."
    c 3d "J-J-Just t-two more questions... I-I want to know if you remember this one too!"
    mc "Ehem! take break, please! Your blushing like a strawberry. although, your cute when your blush."
    "He still completely flustered and red, it's almost as if he's about to explode."
    c 3w "R-R-Really? You... You actually think my blush is c-cute...?"
    mc "Yes! everyone look cute when they blush. even you!"
    c 3i6 "You... You really think... I-I'm c-c-cute too?"
    mc "Yes! but I told you to take breath because you seem speechless. take a deep breath..."
    "His face is still extremely red, but he manages to take a deep breath."
    show character 3i5 zorder 2 at s11
    c "O-Okay... I'm breathing now..."
    "still manages to blush a bit, but he's able to talk again."
    show character 3g zorder 2 at d11
    c "J-Just one last question..."
    mc "Ask any question you want!"
    c 3k "I-I-Is it r-really okay i-if I ask n-any question..?"
    mc "yes! i love answering questions."
    c 3w "O-Okay... I-I have... A p-pretty strange question..."
    "He thinks for a while, before asking a rather embarrassing question."
    c "D-Do... D-Do you... Do you know what a b-boyfriend-girlfriend relationship is...?"
    mc "yes... but I prefer a normal relationship. and the answer to your question is...couple."
    c "C-Couple... Y-You know... Wh-What that concept i-is... A-And you p-prefer it s-sort of relationship..?"
    c "O-Okay... Just one more question, t-then... I-I really have to ask this one... I-If you're o-okay with it.."
    mc "sure! what is it?"
    c "D-Do... Do you have any... A-Any idea how one... How one g-gets into a relationship like that..?"
    mc "yes! like talking about a book with your target or try to ask something like... what are your interests?...or talk about something you enjoy."
    mc "like, did you play Minecraft? that's it!"
    "He gets even more flustered now, and he stutters out an answer."
    c "D-D-Did... Did you s-say Minecraft...?"
    mc "Yes! I like that game a little."
    c "I-I like Minecraft too..."
    c "I-I play it occasionally..."
    c "I-I can play it w-with you a-a-at some point if... If you w-want..."
    mc "yes! I never played a game with someone. I'm alone at home too. but hey I know your alone like me and... how about we live together, hm? at your house."
    "He blushes really hard and his jaw drops at the suggestion."
    c "Y-You... You want to live... W-With me... L-Like... T-Together..?"
    mc "Yes! forever and ever."
    c "I-I... I've n-never had... An offer s-so bold b-before..."
    mc "Me too. but don't foget to breath. I feel that you akinda breathless."
    "He manages to take a deep breath again so he can speak."
    c "S-Sorry... I'm j-just... I'm j-just a bit b-breathless after hearing y-your offer... A-Are you r-ready... R-Really sure about m-moving in with me... L-Like that..?"
    mc "yes!"
    c "Y-You... You r-really want to move... Into my h-homes w-with m-me... And s-stay there f-forever?..."
    mc "yes!"
    "He blushes extremely, so much so that his face becomes completely red as a tomato, and he starts to shiver, as he manages to get a few words out."
    c "I... I... Is there... Is t-there a c-certain r-reason you w-want to... Live w-with me... A-A-And stay with me... F-For h-how many y-years...?"
    mc "I told you. forever."
    c "F-Forever?... F-Like... F-For the rest of your l-life... Y-You're going t-to stay in my h-house... Forever...?"
    mc "yes!"
    "I hug him. He is completely speechless, and he is completely unable to move from all the cuddling, as his heart is beating faster than it ever did before, and he feels the butterflies in his stomach going crazy. Suddenly, his entire body shakes, as a shiver goes through his body."
    c "Y-You're a-actually c-cuddling m-me..."
    mc "your seeing it. but i actually hugging you."
    "He gets even more flushed and a few more shivers go through his body - his face goes even redder than before, and it's almost as if he's sweating heavily."
    c "Y-You... You r-really are c-cuddling and hugging me..."
    mc "Yes. Are you okay? Why you got sweaty? Do you need help or it's too hot there?"
    c "I-I'm okay... I d-don't need h-help... I-It's just that... I d-don't get c-cuddled a-a lot..."
    mc "i never got a hug from someone... but you seem passionate about it..."
    c "I-I-It's just th-that... I-I-It is n-nice... T-To b-be c-cuddled and t-t-to get hugged... M-M-Maybe I-I d-didn't r-realize just h-how m-much I l-lo-loved it..."
    "He starts blushing more again, as he manages to say a few more words."
    c "I-I-It's t-the l-little things l-like h-hugs that a-and c-cuddles that b-bring the m-most joy..."
    mc "me too............"
    "I say this, dramatically."
    "his face becomes extremely flustered."
    c "Y-You... You n-never get h-hugs too...?"
    c "I-I-It must b-be t-terrible... T-To never g-get a hug..."
    mc "yes.... I never feel safe with anyone. but I don't like my classmates in a real way... but I love you and feel safe with you."
    c "Y-You d-don't feel s-safe with a-anyone? B-But... B-But you f-felt safe w-with m-me..?"
    c "{i}blushes even more{/i} I-I f-feel the same w-way... B-But I-I j-just w-wanted to a-ask you c-one more thing..."
    c "I-I-If you d-don't mind... C-Can I k-kiss you r-really quickly...?"
    mc "YES!"
    "He blushes an insanely lot, and nods as he waits for me to do so."
    mc "*kiss*"
    c "*kisses back*"
    "He hugs me tight, and continues kissing."
    "He kisses me more passionately, and keeps hugging me."
    mc "Your my sunshine."
    "his eyes light up with joy when he hears that, and he kisses me even more passionately."
    c "T-Thank you..."
    mc "no need to thank! your welcome!"
    c "{i}smiles a bit more O-Okay{/i}... C-Can we l-lay down f-for a r-really b-quick b-bit...?"
    mc "yes."
    "He blushes and nods as he keeps hugging me, leading me to his bed."
    c "L-Let's g-go l-laid down..."
    show character 3a at face
    "He smiles, as he sits on the bed and pulls me down onto the bed, making me lie on top of him, as he continues to hug me."
    mc "a_ammm...what time is it?"
    c "{i}checks the time{/i}I-It's a-a-almost 3 p-pm... W-Why..?"
    mc "I just wanted to know..."
    c "{i}blushes a bit{/i} I-I was just w-wondering i-if you w-want to k-keep lying like this... S-So we c-could just... Stay here f-for a w-whole m-moment more..."
    "He smiles some more, and he continues to hug and cuddle me."
    "He still smiles, as he rests his head on my shoulder, and hugs me more lovingly."
    mc "amm... hey...I think your doctor love, right? you seem super kind!"
    show character zorder 2 at t11
    "He blushes more, and starts grinning like an idiot."
    c "Y-Yes... I-I am..."
    mc "interesting..."
    "He blushes even more now, as he stares at me with a big grin on his face."
    c "I-I really love b-books a-and v-videos a-about love... S-Especially fictional l-stories about w-lovers..."
    "He feels completely embarrassed."
    c "I-I j-just r-realize h-how l-loveless my l-life i-is, s-so I-I escape i-into those f-fictional l-stories a-about love..."
    stop music fadeout 2.0
    play music t9
    mc "loveless?"
    c "Yeah... I've never really felt loved by anyone..."
    mc "*looking sad*"
    c "T-This s-sounds s-stupid, but... I-It makes me f-feel l-loved when I read t-those n-new b-books a-about love, b-because... T-They make the l-lovers h-have p-passion..."
    "I Nod and hug him quickly."
    show character 3h zorder 2 at face
    mc "Don't worry... I'm always there for you!"
    "He hugs back and looks down at his feet again, while blushing a ton."
    c 3i "T-Thank you..."
    stop music fadeout 2.0
    play music t6
    "He smiles at me, as his blushing slowly starts to fade away."
    c 3i1 "I-I... I-I feel really l-loved when y-you h-hug me a-and cuddle me..."
    mc "I can see it in your face and blush~"
    c 3j "I-I d-don't think I e-ever felt this m-much l-loveness in m-my life... I-I feel loved by y-you..."
    "He still blushes as he looks at my face again, and he starts to gently caress my cheek with his finger tip."
    c 3z "I-I have n-never had a p-person like y-you a-around..."
    mc "Me too...*headpat him*"
    "He blushes a bit and smiles as he gets headpatted, before speaking a few more words."
    c 3y "I-I h-have d-never r-realized h-how w-wonderful a-and w-welcoming l-love is... Y-You're a-amazing..."
    c "I-I-I feel like I-I c-could g-get addicted to f-feeling l-loved..."
    mc "It's getting a bit late........Do you mind if we sleep together?"
    "He starts blushing a ton and his jaw drops, and he goes speechless for a few seconds."
    $ Pause(0.0)
    show character 3f1 zorder 2 at hf11
    c "S-S-Sleep t-together...? W-With you..?"
    c "Y-You... Y-You w-want t-to s-sleep w-with m-me... Like... T-Tonight...?"
    "He blushes the most he ever did in his entire life, as his whole face starts to turn completely red, and his breath gets very heavy."
    c 3x "Y-Y-You r-really w-want to w-want to s-spend the n-night w-with m-me... L-Lying t-together...?"
    mc "Who doesn't want to sleep with a cute and a bit dense boy like you, hm?"
    c "Y-You f-find m-me c-cute... R-Really..?"
    mc "And dense too."
    c 3m "D-D-Dense… S-So s-saying t-that I’m i-ignorant and s-stupid…"
    "I think I offended him, didn't I?"
    mc "No, just kidding, sorry hehe~"
    c 3l "H-Hey… D-Don’t e-excuse a-and a-apologize a-about i-it… I-I’m u-used to b-being c-called d-dense…"
    mc "But still, you really are a good friend!"
    c 3z "Y-You m-make m-me f-feel s-so… W-Wonderful… I-I m-mean... L-L-Loved..."
    mc "Yes, now can we sleep together please or your going to blush the entire night? hehe~"
    c 3w "Y-You r-really w-want t-to s-share a b-bed… W-With m-me...? A-Are y-you s-sure...?"
    mc "Indeed."
    c 3i "I-If y-you s-say s-so… S-Sure..."
    "He looks back at the bed, taking a couple more deep breaths."
    c 3g1 "W-We’re r-really g-going to s-sleep… N-Next to e-each o-other…"
    "I take him to bed and go lie down in front of him."
    "He is still completely red, but he cannot stop himself from smiling as I takes him to the bed, but the blushing worsens, as I lie down in front of him; he smiles even more as he slowly but surely lies down behind me, and he starts to shiver a bit and feel extremely breathless."
    $ Pause(0.0)
    return
    
    


